name: Code Quality

on: [pull_request]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP With Tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pdo, xml, bcmath, intl
          coverage: none
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up Composer auth for GitHub
        run: |
          mkdir -p $HOME/.composer
          echo '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}' > $HOME/.composer/auth.json

      - name: Install Composer Dependencies
        run: composer install --prefer-source --no-progress --no-interaction

      - name: Run Laravel Pint (Formatter)
        run: ./vendor/bin/pint

      - name: Run Rector (Code Refactor Check)
        run: ./vendor/bin/rector
