name: Phpstan Static Analysis

on: [pull_request]

jobs:
  phpstan:
    name: Phpstan Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fix Git Safe Directory
        run: git config --global --add safe.directory /app

      - name: Composer Install
        uses: php-actions/composer@v6

      - name: Setup PHP With Tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip
          tools: composer:v2

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install Phpstan Globally
        run: composer global require phpstan/phpstan

      - name: Run Phpstan Static Analysis
        run: ~/.composer/vendor/bin/phpstan analyse assets/ config/ src/
